[tool.poetry]
name = "clovers-groupmate-waifu"
version = "0.1.0r2"
description = ""
authors = ["KarisAya <1048827424@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
clovers-apscheduler = "^0.1.3"
clovers = {extras = ["linecard", "tools"], version = "^0.1.4"}



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
